#!/usr/bin/env zsh

# pywall
. "${HOME}/.cache/wal/colors.sh"

# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Workspaces
if xrandr --query | grep "VIRTUAL1 connected"; then
    bspc monitor DP1 -d '2' '3' '4' '5'
    bspc monitor VIRTUAL1 -d '1'
    nitrogen  --restore
else
    bspc monitor DP1 -d '1' '2' '3' '4' '5'
    feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"
fi

# bspwm config
bspc config remove_unplugged_monitors 				true
bspc config remove_disabled_monitors 			  	true
bspc config top_padding							    5
bspc config right_padding						    5
bspc config left_padding						    5
bspc config bottom_padding						    5
bspc config border_width 						    1
bspc config border_radius 						    10
bspc config window_gap 							    1
bspc config focus_follows_pointer 				  	true
bspc config split_ratio 						    0.5
bspc config single_monocle 						    true
bspc config borderless_monocle 					    false
bspc config gapless_monocle 					    false
bspc config normal_border_color 				    "$color1"
bspc config active_border_color 				    "$color2"
bspc config focused_border_color 				    "$color15"
bspc config presel_feedback_color 				  	"$color1"
bspc config pointer_modifier					    mod4
bspc config pointer_action1						    move
bspc config pointer_action3						    resize_side
bspc config pointer_action2						    resize_corner

# Keybord (Shortcut) Setup
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Setup Compositer
picom --config "$HOME"/.config/bspwm/picom.conf &

# Notification Setup
bspdunst

# Effects
easyeffects --gapplication-service &

# Autolock
xss-lock -- betterlockscreen -l &

# Cursor
xsetroot -cursor_name left_ptr
