#!/usr/bin/env bash

# Set environment variables
DIR="$HOME/.config/bspwm"
export PATH="$DIR/scripts:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'

# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Setup desktops for each monitor
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
done

# bspwm config
bspc config external_rules_command "$DIR"/scripts/ExternalRules

bspc config window_gap                2
bspc config split_ratio               0.51
bspc config single_monocle            true
bspc config borderless_monocle        false
bspc config gapless_monocle           false

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

# Set the border colors.
bspc config border_width              1
bspc config normal_border_color       "#181825"
bspc config active_border_color       "#f38ba8"
bspc config focused_border_color      "#cba6f7"
bspc config presel_feedback_color     "#89b4fa"


# Display Setup
export DISPLAY=":0"

if ! xrandr --query | grep -q "1920x1080"; then
    xrandr --newmode "1920x1080" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
    xrandr --addmode DP1 "1920x1080"
    xrandr --output DP1 --mode "1920x1080"
fi

# Wallpaper
sh "$HOME/.fehbg"

# Launch fastcompmgr 
pidof -q fastcompmgr || { fastcompmgr -o 0.7 -c -C & }

# Reload sxhkd daemon
pidof -q sxhkd || { sxhkd -c "${DIR}"/sxhkdrc & }

# Launch dunst notification daemon
pidof -q dunst || { dunst -config "${DIR}"/dunstrc & }

# Spotify
pidof -q spotifyd || { spotifyd --config-path $HOME/.config/spotifyd/spotifyd.conf & }

# Fix cursor
xsetroot -cursor_name left_ptr
