#!/usr/bin/env bash

# Set the player
[ -n "$(pgrep spotify_player)" ] && Control="spotify_player" || Control="mocp"


case $Control in
    mocp)
        case $1 in
            --next)
                mocp --next
                ;;
            --previous)
                mocp --previous
                ;;
            --toggle)
                mocp --toggle-pause
                ;;
            --stop)
                mocp --stop
                ;;
        esac
        ;;
    *)
        case $1 in
            --next)
                playerctl --player=$Control next
                ;;
            --previous)
                playerctl --player=$Control previous
                ;;
            --toggle)
                playerctl --player=$Control play-pause
                ;;
            --stop)
                playerctl --player=$Control stop
                ;;
            --title)
                title=$(playerctl --player=$Control metadata --format "{{title}}")
                echo "${title:-Play Something}"
                ;;
            --artist)
                artist=$(playerctl --player=$Control metadata --format "{{artist}}")
                echo "${artist:-No Artist}"
                ;;
            --status)
                status=$(playerctl --player=$Control status)
                echo "${status:-Stopped}"
                ;;
            --player)
                echo "--player=$Control"
                ;;
            --position)
                position=$(playerctl --player=$Control position --format "{{ duration(position) }}")
                echo "${position:-0:00}"
                ;;
            --positions)
                positions=$(playerctl --player=$Control position | sed 's/..\{6\}$//')
                echo "${positions:-0}"
                ;;
            --length)
                length=$(playerctl --player=$Control metadata --format "{{ duration(mpris:length) }}")
                echo "${length:-0:00}"
                ;;
            --lengths)
                lengths=$(playerctl --player=$Control metadata mpris:length | sed 's/.\{6\}$//')
                echo "${lengths:-0}"
                ;;
            --shuffle)
                shuffle=$(playerctl --player=$Control shuffle)
                echo "${shuffle:-Off}"
                ;;
            --loop)
                loop=$(playerctl --player=$Control loop)
                echo "${loop:-None}"
                ;;
        esac
esac 2>/dev/null
