#!/usr/bin/env bash

case "$1" in
    --menu)
        rofi -show drun -theme "$HOME"/.config/bspwm/rofi/launchers/style.rasi
    ;;
    --terminal)
        kitty
    ;;
    --floating)
        kitty --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495
    ;;
    --update)
        kitty --hold --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495 -e Updates --update-system
    ;;
    --checkupdates)
        kitty --hold --class=Updating -o initial_window_width=457 -o initial_window_height=496 -e Updates --print-updates
    ;;
    --screenshot)
        ScreenShoTer
    ;;
    --powermenu)
        PowerMenu
    ;;
    --nvim)
        kitty -e nvim
    ;;
    --music)
        kitty --class=FloaTerm -o initial_window_width=637 -o initial_window_height=412 -e spotify_player
    ;;
    --filemanager)
        kitty -e yazi
    ;;
    --browser)
        zen-browser
    ;;
    --editor)
        code
    ;;
    --zededitor)
        zed
    ;;
    --obsidian)
        obsidian
    ;;
    --discord)
        vesktop
    ;;
    --postman)
        postman
    ;;
    *)
        echo "Invalid Option"
    ;;
esac
