#!/bin/bash

get_total_updates() {
    local regular_updates aur_updates
    regular_updates=$(checkupdates 2>/dev/null | wc -l)
    aur_updates=$(yay -Qua 2>/dev/null | wc -l)
    echo $((regular_updates + aur_updates))
}

get_list_updates() {
    echo -e "\033[1m\033[34mRegular updates:\033[0m"
    checkupdates | sed 's/->/\x1b[32;1m\x1b[0m/g'
}

get_list_aur_updates() {
    echo -e "\n\033[1m\033[34mAUR updates available:\033[0m"
    yay -Qua | sed 's/->/\x1b[32;1m\x1b[0m/g'
}

print_updates() {
    local total_updates
    total_updates=$(get_total_updates)

    if ((total_updates > 0)); then
        echo -e "\033[1m\033[33mThere are $total_updates updates available:\033[0m\n"
        get_list_updates
        get_list_aur_updates
    else
        echo -e "\033[1m\033[32mYour system is already updated!\033[0m"
    fi
}

update_system() {
    yay -Syu --noconfirm # --nocombinedupgrade
}

display_help() {
    echo -e "Updates [options]

Options:
    --get-updates      Get the number of updates available.
    --print-updates    Print the available updates (regular + AUR).
    --update-system    Update your system, including AUR packages.\n"
}

case "$1" in
    --get-updates) get_total_updates ;;
    --print-updates) print_updates ;;
    --update-system) update_system ;;
    --help) display_help ;;
esac
