#!/usr/bin/env bash

# This script handles window management rules based on window class and instance.

wid="$1"
class="$2"
instance="$3"
consequences="$4"

# Define window management rules based on window class
case "$class" in
    FloaTerm)
        eval "$consequences"
        [ "$state" ] || echo "state=floating center=on"
        ;;
    Updating)
        eval "$consequences"
        [ "$state" ] || echo "state=floating sticky=on center=on"
        ;;
    mpv)
        eval "$consequences"
        [ "$state" ] || echo "state=tiled focus=on center=on"
        ;;
    Viewnior)
        eval "$consequences"
        [ "$state" ] || echo "state=floating focus=on center=on"
        ;;
    zapzap|TelegramDesktop|discord)
        eval "$consequences"
        [ "$state" ] || echo "state=pseudo_tiled desktop=^4 follow=on rectangle=930x617+0+0"
        ;;
    retroarch)
        eval "$consequences"
        [ "$state" ] || echo "state=pseudo_tiled desktop=^6 follow=on"
        ;;
    Pavucontrol)
        eval "$consequences"
        [ "$state" ] || echo "state=floating center=on"
        ;;
    Virt-manager)
        eval "$consequences"
        [ "$state" ] || echo "state=floating desktop=^5 follow=on center=on"
        ;;
    ranger)
        eval "$consequences"
        [ "$state" ] || echo "state=pseudo_tiled desktop=^2 rectangle=966x576+0+0 follow=on"
        ;;
    brave)
        eval "$consequences"
        [ "$state" ] || echo "desktop=^3 follow=on"
        ;;
    Transmission-gtk)
        eval "$consequences"
        [ "$state" ] || echo "desktop=^6 follow=on"
        ;;
    spotify)
        eval "$consequences"
        [ "$state" ] || echo "desktop=^6 follow=on"
        ;;
esac

# Define additional window management rules based on window instance
case "$instance" in
    Toolkit)
        eval "$consequences"
        [ "$state" ] || echo "state=floating sticky=on rectangle=500x290+1054+593"
        ;;
esac
