#!/usr/bin/env bash

folder_name="$HOME/Pictures/Wallpapers/"
seq_file_path="$HOME/.cache/sequence.txt"

function adjust_sequence {
    if [ -f "$seq_file_path" ]; then
        last_sequence=$(cat "$seq_file_path")
    else
        last_sequence=0
    fi
    echo "$last_sequence"  # Return last_sequence
}

function right_action {
    current_sequence=$(adjust_sequence)
    ((current_sequence++))
    file_name="b-$(printf "%03d" "$current_sequence").jpg"
    if [ ! -e "${folder_name}${file_name}" ]; then
        current_sequence=1
        file_name="b-$(printf "%03d" "$current_sequence").jpg"
    fi
    wal_name="${folder_name}${file_name}"
    feh --bg-fill "$wal_name"
    echo "$current_sequence" > "$seq_file_path"
}

function left_action {
    current_sequence=$(adjust_sequence)
    ((current_sequence--))
    file_name="b-$(printf "%03d" "$current_sequence").jpg"
    if [ ! -e "${folder_name}${file_name}" ]; then
        current_sequence=$(find $folder_name -maxdepth 1 -type f -name "*.jpg" | wc -l)
        file_name="b-$(printf "%03d" "$current_sequence").jpg"
    fi
    wal_name="${folder_name}${file_name}"
    feh --bg-fill "$wal_name"
    echo "$current_sequence" > "$seq_file_path"
}

function read_single_key {
    old=$(stty -g)
    stty -icanon -echo min 1 time 0
    eval "$1=\$(dd bs=1 count=1 2>/dev/null)"
    stty "$old"
}

function handle_exit {
    if [ -d "$HOME/.cache/wal" ]; then
        rm -r "$HOME/.cache/wal"
    fi
    # Generating new colorscheme 
    wal -n -i "$wal_name"
    # creating colorscheme for zathura
    genzathurarc
    # creating dunstrc for dunst
    gendunstrc
    # Applying wallpaper to lockscreen
    betterlockscreen -u "$wal_name"
    exit 0
}

while true; do
    read_single_key keypress
    case "$keypress" in
        '.') right_action ;; 
        ',') left_action ;;  
        *)  
            if [[ "$keypress" == '/' || "$keypress" == 'q' ]]; then
                handle_exit
            fi
            ;;
    esac
done

