#!/usr/bin/env bash
source "$HOME/.cache/wal/colors.sh"

file_path="$HOME/.config/bspwm/rofi/shared/colors.rasi"

if [ -f "$file_path" ]; then
    rm "$file_path"
fi

cat <<EOF >"$file_path"
* {
    background:     $background;
    background-alt: $background;
    foreground:     $foreground;
    foreground-alt: $foreground;
    selected:       $color2;
    active:         $color1;
    urgent:         $color3;
}
EOF
