#!/bin/bash

## Get data
STATUS="$(playerctl --player=spotify_player,chromium status)"
COVER="/tmp/.music_cover.jpg"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
	if [[ "$STATUS" == "Playing" ]]; then
		echo ""
	else
		echo "喇"
	fi
}

## Get song
get_song() {
	song="$(playerctl --player=spotify_player,chromium metadata title)"
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi
}

## Get artist
get_artist() {
	artist="$(playerctl --player=spotify_player,chromium metadata artist)"
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "$artist"
	fi
}

## Get time
get_time() {
    current_position=$(playerctl --player=spotify_player,chromium position)
    if [[ -z "$current_position" ]]; then
        echo "0"
        return
    fi

    total_duration=$(playerctl --player=spotify_player,chromium metadata mpris:length)
    if [[ -z "$total_duration" ]]; then
        echo "0"
        return
    fi

    # Calculate percentage
    percentage=$(awk "BEGIN {printf \"%.2f\n\", (${current_position} / (${total_duration} / 1000000)) * 100}")

    echo "${percentage}"
}



## Get cover
get_cover() {
	# Fetch album art URL from playerctl --player=spotify_player,chromium
	art_url="$(playerctl --player=spotify_player,chromium metadata mpris:artUrl)"

	# Check if the URL is not empty and download the image
	if [ -n "$art_url" ]; then
		curl -s "$art_url" > "${COVER}"

		# Check if the file was downloaded successfully
		if [ -f "${COVER}" ]; then
			echo "${COVER}"
		fi
	else
		echo "images/music.png"
	fi
}

## Execute accordingly
case "$1" in
	"--song")
		get_song
		;;
	"--artist")
		get_artist
		;;
	"--status")
		get_status
		;;
	"--time")
		get_time
		;;
	"--cover")
		get_cover
		;;
	"--toggle")
		playerctl --player=spotify_player,chromium play-pause
		;;
	"--next")
		playerctl --player=spotify_player,chromium next
		;;
	"--prev")
		playerctl --player=spotify_player,chromium previous
		;;
esac
