#!/usr/bin/env bash

theme="$HOME/.config/bspwm/rofi/common/style.rasi"
# Theme Elements
prompt='Applications'
mesg='Run Applications'

# Options
layout=$(cat ${theme} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
    option_1=" Kitty"
    option_2=" Find"
    option_3=" Code"
    option_4=" Ranger"
    option_5=" Vim"
else
    option_1=""
    option_2=""
    option_3=""
    option_4=""
    option_5=""
fi

# Rofi CMD
rofi_cmd() {
    rofi -theme-str 'textbox-prompt-colon {str: "";}' \
        -dmenu \
        -p "$prompt" \
        -mesg "$mesg" \
        -markup-rows \
        -theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Execute Command
run_cmd() {
    if [[ "$1" == '--opt1' ]]; then
        kitty
    elif [[ "$1" == '--opt2' ]]; then
        kitty -e fzf --preview 'bat --color always --style=plain {}'
    elif [[ "$1" == '--opt3' ]]; then
        code
    elif [[ "$1" == '--opt4' ]]; then
        kitty -e ranger
    elif [[ "$1" == '--opt5' ]]; then
        kitty -e nvim
    fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
    run_cmd --opt1
    ;;
$option_2)
    run_cmd --opt2
    ;;
$option_3)
    run_cmd --opt3
    ;;
$option_4)
    run_cmd --opt4
    ;;
$option_5)
    run_cmd --opt5
    ;;
esac
